openapi: 3.0.0
 
info:
  version: 1.0.0
  title: Library Service
  description: The library service

servers: 
  # Added by API Auto Mocking Plugin
  #- description: SwaggerHub API Auto Mocking
  #  url: https://virtserver.swaggerhub.com/ALIDRISSIAKRAM/api-rest-formation-book/1.0.0
  - description: dev 
    url: 'http://localhost:8080'
    

tags:
  - name: "Library"
  - name : "Users"
 
 
paths:
 
  /books:
    get:
      summary: This is summary
      tags:
        - "Library"
      description: This is a description
      operationId: getAllBooksInLibrary
      responses:
        "200":
          description: This means its ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
        #Aajouter
        "400":
          description: Bad resquest
        "401":
          description: Unauthorized
    post:
      summary: Book creation
      tags: 
        - "Library"
      operationId: createBook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        "201":
          description: Book successfully created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: The ID of the created book
              example:
                id: 12345
        "400":
          description: Bad request
        "401":
          description: Unauthorized
  /books/{idbook}:
    get:
      summary: Obtenir les informations d'un livre
      tags: 
        - "Library"
      description: Récupère les détails d'un livre basé sur son identifiant.
      parameters:
        - name: idbook
          in: path
          required: true
          description: L'identifiant du livre à récupérer.
          schema:
            type: string
      responses:
        '200':
          description: Détails du livre récupéré avec succès.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '400':
          description: Requête invalide. L'identifiant du livre n'est pas valide.
        '404':
          description: Livre non trouvé. Aucun livre ne correspond à l'identifiant fourni.
        '500':
          description: Erreur interne du serveur.
components:
 
  schemas:
 
    Book:
      description: This is the book model
      type: object
      required: 
        - name
      properties:
        name:
          description: The name of book
          type: string
        bookAuthor:
          description: name of author
          type: string
        #Aajouter
        price:
          description: price of product
          type: integer